#!/bin/bash

../../../vendor/bin/propel reverse --database-name="amigosecreto"  "pgsql:host=localhost;dbname=amigosecreto;user=amigosecreto;password=amigosecreto" --output-dir="."
../../../vendor/bin/propel model:build  --output-dir="../../models/propel"

../../../artisan dump-autoload
